version: "3.8"
services:
  web:
    build: ./django-blog
    image: "${IMAGE_REPO_URL}:djangoblog"
    command: gunicorn --bind 0.0.0.0:8000 website.wsgi
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
    ports:
      - "8000:8000"
